sudo: false
language: node_js
node_js:
  - 5
notifications:
  slack:
    secure: ufUqs6gfkMaKG/rNVQMzzYlvPS6n78oyvvSR0Y6Z9HaVsxnk2F5O1OM3M4IN0N4GxsbCToTuA8t64Dc6Qwx+t3ScmjqyWlxUrIzh3vkX41GoT4DK68IL4sCwQGR9ODtgoQetiXoEuZIvlFjMA2hVwWTku+nDXPN8kuN00n67NwzxWVDomRkwFRgqSPcoFxg2Dq+V909wBAZMU3nhyhoaMygkFRPnsHtyWhDAWbbznQQ/adlLnnGgK0Q3+qcCwvKtMt/lPq1utI7DUxxebA7auFSuunwou+iCMBVFUCbQUeupGnhfMnkyZh9a2V3ny3ixJtbgJKwdVMu8aE/2k0wLAHtnZOUWnsbbrruJr01IE9Gg9NLHScPQHjd89iq2CWYSdGrEwcGlztbwuYWu5qjzwF8R0xfPkYFa4+xq9TQpQ2ilrYkwKJ1j2hb7GS34DGcbRylOAMGMIFcYcneAVox2zy2tR5BSwkJflL5a2Ei1AIrtdx+930kDa7XLl181ueYLlbwbRg7ksOzET07wavdQNhxwyLUPBP49PH+0aM0Z+z/mHYJJHX5/RNXalhd7PGw4vHxVDsCVCit0SjifAO1xHgTwWUCD7qroZAC4qPe1rcHA334f9JfHCh/c9ULu8V7NTM5nVV2R+qi5/hsa5vP6BmHb2RLAS9utPHU/4CGs9t0=
